name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postfix: [ "231","233","242","243" ]
        include:
          - product: "231"
            distribution: "zulu"
            java: "17"
          - product: "233"
            distribution: "zulu"
            java: "17"
          - product: "242"
            distribution: "zulu"
            java: "21"
          - product: "243"
            distribution: "zulu"
            java: "21"
    steps:
      - name: Checkout the plugin GitHub repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Check repository content
        shell: bash
        run: pwd && ls -la

      - name: Test plugin
        shell: bash
        run: ./gradlew test
        env:
          ZOWE_EXPLORER_POSTFIX: ${{ matrix.product }}

      - name: Build plugin's binary
        shell: bash
        run: ./gradlew buildPlugin
        env:
          ZOWE_EXPLORER_POSTFIX: ${{ matrix.product }}

      - name: Prepare Plugin Artifact
        id: artifact
        shell: bash
        run: |
          cd ${{ github.workspace }}/build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content
          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT
          echo "zip artifact name:"
          echo "$FILENAME"

      - name: Publish built plugin to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./build/distributions/content/*/*
